name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (z.B. 1.2.0)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Resolve version
        id: ver
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "VERSION=${GITHUB_REF##*/v}" >> "$GITHUB_ENV"
          else
            echo "VERSION=${{ github.event.inputs.version }}" >> "$GITHUB_ENV"
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set release version in POM
        run: mvn --batch-mode versions:set -DnewVersion=$VERSION

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare Maven environment
        run: export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"

      - name: Publish to Apache Maven Central
        run: mvn deploy -PsonatypeDeploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate release notes
        id: notes
        run: |
          PREV=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          if [[ -n "$PREV" ]]; then
            CHANGELOG="$(git log $PREV..HEAD --pretty=format:'- %s' --no-merges)"
          else
            CHANGELOG="$(git log --pretty=format:'- %s' --no-merges -n 50)"
          fi

          cat <<EOF > RELEASE_NOTES.md

          ## Changes
          $CHANGELOG

          ## Maven Central
          \`\`\`xml
          <dependency>
            <groupId>io.github.afrouper</groupId>
            <artifactId>sungrow-api-client</artifactId>
            <version>$VERSION</version>
          </dependency>
          \`\`\`

          EOF

      - name: Create release (and upload JARs)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body_path: RELEASE_NOTES.md
          files: |
            target/sungrow-api-client-${{ env.VERSION }}.jar
            target/sungrow-api-client-${{ env.VERSION }}-sources.jar
            target/sungrow-api-client-${{ env.VERSION }}-javadoc.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

