package de.afrouper.server.sungrow.api.dto;

import com.google.gson.annotations.SerializedName;

public enum DeviceType {
    @SerializedName("1")
    Inverter,
    @SerializedName("2")
    Container,
    @SerializedName("3")
    Grid_Connection_Point,
    @SerializedName("4")
    Combiner_Box,
    @SerializedName("5")
    Meteo_Station,
    @SerializedName("6")
    Transformer,
    @SerializedName("7")
    Meter,
    @SerializedName("8")
    UPS,
    @SerializedName("9")
    Data_Logger,
    @SerializedName("10")
    PV_String,
    @SerializedName("11")
    Plant,
    @SerializedName("12")
    Circuit_Protection,
    @SerializedName("13")
    Splitting_Device,
    @SerializedName("14")
    Energy_Storage_System,
    @SerializedName("15")
    Sampling_Device,
    @SerializedName("16")
    EMU,
    @SerializedName("17")
    Unit,
    @SerializedName("18")
    Temperature_Humidity_Sensor,
    @SerializedName("19")
    Intelligent_Power_Distribution_Cabinet,
    @SerializedName("20")
    Display_Device,
    @SerializedName("21")
    AC_Power_Distributed_Cabinet,
    @SerializedName("22")
    Communication_Module,
    @SerializedName("23")
    System_BMS,
    @SerializedName("24")
    Array_BMS,
    @SerializedName("25")
    DC_DC,
    @SerializedName("26")
    Energy_Management_System,
    @SerializedName("27")
    Tracking_System,
    @SerializedName("28")
    Wind_Energy_Converter,
    @SerializedName("29")
    SVG,
    @SerializedName("30")
    PT_Cabinet,
    @SerializedName("31")
    Bus_Protection,
    @SerializedName("32")
    Cleaning_Device,
    @SerializedName("33")
    Direct_Current_Cabinet,
    @SerializedName("34")
    Public_Measurement_and_Control,
    @SerializedName("37")
    Energy_Storage_System_2,
    @SerializedName("43")
    Battery,
    @SerializedName("44")
    Battery_Cluster_Management_Unit,
    @SerializedName("45")
    Local_Controller,
    @SerializedName("52")
    Battery_System_Controller
}
